// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5urwsvi6U6rY5Ay2pl_nnjHCQc1h6bNA',
    appId: '1:757346680809:android:ec41f0418f237965521578',
    messagingSenderId: '757346680809',
    projectId: 'jobility-95279',
    storageBucket: 'jobility-95279.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKqvg7Yp0F9zStRwLbYELrrxKfoS506Xk',
    appId: '1:757346680809:ios:4e80db598cf227f8521578',
    messagingSenderId: '757346680809',
    projectId: 'jobility-95279',
    storageBucket: 'jobility-95279.appspot.com',
    iosBundleId: 'com.example.jobFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXRIwdME0HYwYJk7ZGQg6s8dz3-plP2Rk',
    appId: '1:624311592722:ios:363fe5b1727e18edda75cb',
    messagingSenderId: '624311592722',
    projectId: 'jobility-c1d00',
    storageBucket: 'jobility-c1d00.appspot.com',
    iosBundleId: 'com.example.jobFinder',
  );

}